config/routes.rb
Rails.application.routes.draw do
  root "products#index"

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews

  def average_rating
    return 0 if reviews.empty?
    reviews.sum(:rating) / reviews.size.to_f
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :rating, presence: true, numericality: {
    greater_than_or_equal_to: 0.5, less_than_or_equal_to: 5
  }
  validates :comment, length: {minimum: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)

    respond_to do |format|
      if @review.save
        ActionCable.server.broadcast(
          "products_channel",
          rating: @review.rating,
          comment: @review.comment
        )
        format.html { redirect_to @review.product, notice: "Review was successfully created." }
      else
        format.html { redirect_to @review.product, alert: "Review was not created" }
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  </head>
  <body>
    <% flash.each do |type, msg| %>
      <div class="relative z-10 mx-4" id="flash">
        <div class="absolute inset-x-0 top-10 w-auto max-w-xs py-3 mx-auto bg-white border rounded-lg shadow-sm border-gray-200" role="alert">
          <div class="flex items-center justify-between mx-4">
            <div class="flex items-center space-x-3">
              <p class="text-lg"> <%= type == "notice" ? "✅" : "❌" %></p>
              <%= content_tag :p, msg, class: "max-w-prose" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="p-6 mx-auto max-w-2xl">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_modal.html.erb
<div id="overlay" class="fixed bg-black w-full h-full bg-opacity-50 top-0 left-0 right-0 bottom-0 hidden"  aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="w-full px-6 max-w-2xl z-20 dialog-position">
    <div class="rounded-lg bg-white p-5">
      <h1 id="modal-title" class="text-3xl mt-4 font-bold">What's your rating?</h1>
      <%= form_with(model: @product.reviews.new, url: product_reviews_path(product_id: @product.id), local: true, class: "flex flex-col space-y-7 md:space-y-9") do |f| %>
        <%= f.label :rating, "Rating", class: "text-2xl mb-4"%>
        <%= react_component("Rating") %>
        <%= f.label :comment, "Review", class: "text-2xl mb-4"%>
        <%= f.text_field :comment, placeholder: "Start typing...", class: "text-lg" %>
        <%= f.submit "Submit review", class: "shadow bg-white border border-gray-300 text-gray-400 font-medium px-3 py-2 rounded text-sm hover:bg-gray-50 cursor-pointer" %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_stars.html.erb
<div class="flex text-xl space-x-1">
  <% 5.times do |index| %>
    <svg width="26" height="26" viewBox="0 0 30 30" fill="currentColor" xmlns="http://www.w3.org/2000/svg" class="<%= class_names(" text-yellow-400": rating > index, "text-gray-200": rating <= index) %>" >
      <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M29.895 11.321c-.235-.674-.806-1.171-1.509-1.274l-8.07-1.245-3.602-7.733C16.377.44 15.732 0 15 0s-1.377.44-1.713 1.07L9.684 8.801 1.57 10.047c-.66.102-1.23.6-1.465 1.274a1.81 1.81 0 00.44 1.904l5.887 6.02-1.406 8.567c-.102.703.205 1.406.762 1.846.337.234.703.336 1.113.336.293 0 .6-.073.908-.234L15 25.776l7.191 3.984c.308.161.615.234.908.234.41 0 .776-.102 1.113-.336.557-.44.864-1.143.762-1.846l-1.406-8.568 5.887-6.019a1.81 1.81 0 00.44-1.904z"
          fill="currentColor"
        />
        <path
          class="<%= class_names(" text-gray-200", "hidden": !((index + 1) - rating == 0.5)) %>"
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M28.3862 10.047C29.0892 10.1495 29.6603 10.6474 29.8947 11.3211C30.129 11.9802 29.9679 12.7271 29.4553 13.2251L23.5677 19.2445L24.9737 27.8122C25.0762 28.5152 24.7687 29.2182 24.2121 29.6576C23.8753 29.8919 23.5092 29.9944 23.0991 29.9944C22.8062 29.9944 22.4986 29.9212 22.191 29.7601L15 25.7764V0C15.7323 0 16.3767 0.439371 16.7135 1.06914L20.3164 8.80207L28.3862 10.047Z"
          fill="currentColor"
        />
  </svg>
<% end %>
</div>

app/views/products/index.html.erb
<h1 class="text-3xl mt-4 mb-4 font-bold">Products</h1>
<ul class="space-y-3">
  <% @products.each do |product| %>
    <%= link_to(product_path(product), class: 'text-lg md:text-xl bg-gray-100 hover:bg-gray-200 rounded-lg p-4 flex justify-between space-x-2') do %>
      <p><%= product.name %></p>
      <div class="w-20 md:w-24">
        <%= render "stars", rating: product.average_rating.floor %>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/products/show.html.erb
<%= link_to('back to products', root_path, class: 'text-blue-500 text-sm hover:underline my-2') %>
<h1 class="text-5xl mt-4 mb-4 font-bold"><%=  @product.name %></h1>
<% if @product.description %>
  <p class="text-gray-600"><%= @product.description %></p>
<% end %>
<% if @product.average_rating > 0 %>
  <div class="py-6 flex items-center space-x-5">
    <p id="product_average_rating" class="text-5xl"><%= number_with_precision(@product.average_rating, precision: 1) %></p>
    <%= render "products/stars", rating: @product.average_rating.floor %>
  </div>
<% end %>
<hr>
<div class="py-6">
  <div class="flex justify-between items-center">
    <h2 class="font-bold text-xl">Reviews</h2>
    <button id="button-add-review" class="shadow  bg-white border border-gray-300 text-gray-400 font-medium px-2 py-1 rounded text-sm hover:bg-gray-50">Add review</button>
  </div>
  <div class="my-3">
    <div id="reviews" class="grid gap-5 md:grid-cols-8">
      <% @product.reviews.each do |review| %>
        <div class="md:col-span-2">
          <div class="w-32">
            <%= render "products/stars", rating: review.rating %>
          </div>
        </div>
        <p class="md:col-span-6">
          <span class="font-bold"><%= review.rating %></span>
          <span class="text-gray-500">, <%= review.comment %></span>
        </p>
      <% end %>
    </div>
  </div>
</div>
<%= render "products/modal" %>